project:
  type: website
  output-dir: docs

website:
  title: "CS224W-KOR Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/CS224W-KOR
        
format:
  html:
    theme: pulse
    css: styles.css



